#define HUD_MASTER_US_POS(x,y) [safeZoneX + (safeZoneW * 0.5) - ((107 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.5) - ((107 * pixelGridBase * pixelH) * 0.5) + y,107 * pixelGridBase * pixelW,107 * pixelGridBase * pixelH]
#define HUD_OUTLINE_US_POS [0,0,107 * pixelGridBase * pixelW,107 * pixelGridBase * pixelH]
#define HUD_OUTLINE_LINES_US_POS [0,0,107 * pixelGridBase * pixelW,107 * pixelGridBase * pixelH]
#define HUD_OUTLINE_TEXT_US_POS [0,0,107 * pixelGridBase * pixelW,107 * pixelGridBase * pixelH]

#define HUD_AIR_PROGRESS_US_POS(x,y) [safeZoneX + (safeZoneW * 0.37295) - ((8.47 * pixelGridBase * pixelW) * 0.37295) + x,safeZoneY + (safeZoneH * -0.045) - ((8.47 * pixelGridBase * pixelH) * -0.045) + y,8.47 * pixelGridBase * pixelW,8.47 * pixelGridBase * pixelH]
#define HUD_BATT_PROGRESS_US_POS(x,y) [safeZoneX + (safeZoneW * 0.37295) - ((8.47 * pixelGridBase * pixelW) * 0.37295) + x,safeZoneY + (safeZoneH * -0.0206) - ((8.47 * pixelGridBase * pixelH) * -0.0206) + y,8.47 * pixelGridBase * pixelW,8.47 * pixelGridBase * pixelH]

//#define HUD_EXT_ATM_US_POS [1.58,0.795,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_EXT_ATM_US_POS(x,y) [safeZoneX + (safeZoneW * 0.6745) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.088) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_ENVIRON_RAD_US_POS [1.4675,0.80,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_ENVIRON_RAD_US_POS(x,y) [safeZoneX + (safeZoneW * 0.628) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.061) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_RAD_TOTAL_US_POS [1.4675,0.745,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_RAD_TOTAL_US_POS(x,y) [safeZoneX + (safeZoneW * 0.628) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.09) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_TEMP_INT_US_POS [1.2,0.745,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_TEMP_INT_US_POS(x,y) [safeZoneX + (safeZoneW * 0.52) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.061) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_TEMP_EXT_US_POS [1.2,0.80,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_TEMP_EXT_US_POS(x,y) [safeZoneX + (safeZoneW * 0.52) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.09) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_TME_DANG_TEMP_US_POS [1.1175,0.80,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_TME_DANG_TEMP_US_POS(x,y) [safeZoneX + (safeZoneW * 0.48) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.09) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_TEMP_WATT_US_POS [1.1175,0.745,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_TEMP_WATT_US_POS(x,y) [safeZoneX + (safeZoneW * 0.48) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.061) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_BEARING_US_POS [1.07,0.845,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_BEARING_US_POS(x,y) [safeZoneX + (safeZoneW * 0.4625) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.115) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_GRID_US_POS [1.158,0.88,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_GRID_US_POS(x,y) [safeZoneX + (safeZoneW * 0.5) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.134) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_RANGE_US_POS [1.246,0.845,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_RANGE_US_POS(x,y) [safeZoneX + (safeZoneW * 0.5375) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.115) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_AIR_EST_TIME_US_POS [0.841,0.715,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_AIR_EST_TIME_US_POS(x,y) [safeZoneX + (safeZoneW * 0.3833) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.068) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
//#define HUD_BATT_EST_TIME_US_POS [0.841,0.83,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_BATT_EST_TIME_US_POS(x,y) [safeZoneX + (safeZoneW * 0.3833) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.133) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]

//#define HUD_MAG_COUNT_US_POS [2.0325,2.1,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_MAG_COUNT_US_POS(x,y) [safeZoneX + (safeZoneW * 0.861) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.805) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_FIRE_MODE_US_POS [2.0775,2.255,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_FIRE_MODE_US_POS(x,y) [safeZoneX + (safeZoneW * 0.88) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.889) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_WEAPON_ZERO_US_POS [2.0775,2.3,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_WEAPON_ZERO_US_POS(x,y) [safeZoneX + (safeZoneW * 0.88) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9145) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_GRENADE_COUNT_US_POS [2.1142,2.34,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
#define HUD_GRENADE_COUNT_US_POS(x,y) [safeZoneX + (safeZoneW * 0.8945) - ((5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.938) - ((5 * pixelGridBase * pixelH) * 0.5) + y,5 * pixelGridBase * pixelW,5 * pixelGridBase * pixelH]
//#define HUD_WEAPON_PRIMARY_US_POS [2.09,2.065,8.5 * pixelGridBase * pixelW,8.5 * pixelGridBase * pixelH]
#define HUD_WEAPON_PRIMARY_US_POS(x,y) [safeZoneX + (safeZoneW * 0.9) - ((8.5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.815) - ((8.5 * pixelGridBase * pixelH) * 0.5) + y,8.5 * pixelGridBase * pixelW,8.5 * pixelGridBase * pixelH]
//#define HUD_WEAPON_SECONDARY_US_POS [2.315,2.1475,4 * pixelGridBase * pixelW,4 * pixelGridBase * pixelH]
#define HUD_WEAPON_SECONDARY_US_POS(x,y) [safeZoneX + (safeZoneW * 0.973) - ((4 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8225) - ((4 * pixelGridBase * pixelH) * 0.5) + y,4 * pixelGridBase * pixelW,4 * pixelGridBase * pixelH]
//#define HUD_WEAPON_LAUNCHER_US_POS [2.315,2.245,4 * pixelGridBase * pixelW,4 * pixelGridBase * pixelH]
#define HUD_WEAPON_LAUNCHER_US_POS(x,y) [safeZoneX + (safeZoneW * 0.973) - ((4 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8725) - ((4 * pixelGridBase * pixelH) * 0.5) + y,4 * pixelGridBase * pixelW,4 * pixelGridBase * pixelH]
//#define HUD_WEAPON_GRENADE_US_POS [2.205,2.36,3.5 * pixelGridBase * pixelW,3.5 * pixelGridBase * pixelH]
#define HUD_WEAPON_GRENADE_US_POS(x,y) [safeZoneX + (safeZoneW * 0.925) - ((3.5 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.935) - ((3.5 * pixelGridBase * pixelH) * 0.5) + y,3.5 * pixelGridBase * pixelW,3.5 * pixelGridBase * pixelH]

#define HUD_SQUAD_NAME0_US_POS(x,y) [safeZoneX + (safeZoneW * 0.03) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.83) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_HR0_US_POS(x,y) [safeZoneX + (safeZoneW * 0.0546) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.83) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_BP0_US_POS(x,y) [safeZoneX + (safeZoneW * 0.081) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.83) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_DATALINK0_US_POS(x,y) [safeZoneX + (safeZoneW * 0.1133) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.83) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]

#define HUD_SQUAD_NAME1_US_POS(x,y) [safeZoneX + (safeZoneW * 0.03) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8486) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_HR1_US_POS(x,y) [safeZoneX + (safeZoneW * 0.0546) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8486) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_BP1_US_POS(x,y) [safeZoneX + (safeZoneW * 0.081) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8486) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_DATALINK1_US_POS(x,y) [safeZoneX + (safeZoneW * 0.1133) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8486) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]

#define HUD_SQUAD_NAME2_US_POS(x,y) [safeZoneX + (safeZoneW * 0.03) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8672) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_HR2_US_POS(x,y) [safeZoneX + (safeZoneW * 0.0546) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8672) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_BP2_US_POS(x,y) [safeZoneX + (safeZoneW * 0.081) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8672) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_DATALINK2_US_POS(x,y) [safeZoneX + (safeZoneW * 0.1133) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8672) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]

#define HUD_SQUAD_NAME3_US_POS(x,y) [safeZoneX + (safeZoneW * 0.03) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8858) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_HR3_US_POS(x,y) [safeZoneX + (safeZoneW * 0.0546) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8858) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_BP3_US_POS(x,y) [safeZoneX + (safeZoneW * 0.081) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8858) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_DATALINK3_US_POS(x,y) [safeZoneX + (safeZoneW * 0.1133) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.8858) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]

#define HUD_SQUAD_NAME4_US_POS(x,y) [safeZoneX + (safeZoneW * 0.03) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9044) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_HR4_US_POS(x,y) [safeZoneX + (safeZoneW * 0.0546) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9044) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_BP4_US_POS(x,y) [safeZoneX + (safeZoneW * 0.081) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9044) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_DATALINK4_US_POS(x,y) [safeZoneX + (safeZoneW * 0.1133) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9044) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]

#define HUD_SQUAD_NAME5_US_POS(x,y) [safeZoneX + (safeZoneW * 0.03) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.923) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_HR5_US_POS(x,y) [safeZoneX + (safeZoneW * 0.0546) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.923) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_BP5_US_POS(x,y) [safeZoneX + (safeZoneW * 0.081) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.923) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_DATALINK5_US_POS(x,y) [safeZoneX + (safeZoneW * 0.1133) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.923) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]

#define HUD_SQUAD_NAME6_US_POS(x,y) [safeZoneX + (safeZoneW * 0.03) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9416) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_HR6_US_POS(x,y) [safeZoneX + (safeZoneW * 0.0546) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9416) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_BP6_US_POS(x,y) [safeZoneX + (safeZoneW * 0.081) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9416) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_DATALINK6_US_POS(x,y) [safeZoneX + (safeZoneW * 0.1133) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9416) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]

#define HUD_SQUAD_NAME7_US_POS(x,y) [safeZoneX + (safeZoneW * 0.03) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9602) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_HR7_US_POS(x,y) [safeZoneX + (safeZoneW * 0.0546) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9602) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_BP7_US_POS(x,y) [safeZoneX + (safeZoneW * 0.081) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9602) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_DATALINK7_US_POS(x,y) [safeZoneX + (safeZoneW * 0.1133) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9602) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]

#define HUD_SQUAD_NAME8_US_POS(x,y) [safeZoneX + (safeZoneW * 0.03) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9788) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_HR8_US_POS(x,y) [safeZoneX + (safeZoneW * 0.0546) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9788) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_BP8_US_POS(x,y) [safeZoneX + (safeZoneW * 0.081) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9788) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_DATALINK8_US_POS(x,y) [safeZoneX + (safeZoneW * 0.1133) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9788) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]

#define HUD_SQUAD_NAME9_US_POS(x,y) [safeZoneX + (safeZoneW * 0.03) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9974) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_HR9_US_POS(x,y) [safeZoneX + (safeZoneW * 0.0546) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9974) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_BP9_US_POS(x,y) [safeZoneX + (safeZoneW * 0.081) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9974) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
#define HUD_SQUAD_DATALINK9_US_POS(x,y) [safeZoneX + (safeZoneW * 0.1133) - ((8 * pixelGridBase * pixelW) * 0.5) + x,safeZoneY + (safeZoneH * 0.9974) - ((8 * pixelGridBase * pixelH) * 0.5) + y,8 * pixelGridBase * pixelW,8 * pixelGridBase * pixelH]
