//PREP(handleUnitHUD);
PREP(initPFH_FireControl);
PREP(initPFH_HudGeneral);
PREP(initPFH_HudInertia);
PREP(updateUnitsNearPlayer);
PREP(updateIFF);
PREP(updateWeaponCrosshair);
PREP(updateNametags);
PREP(updateTargetPosInfo);
PREP(updateWeaponDisplay);
PREP(updateGrenadeDisplay);
PREP(updateGroupDisplay);
PREP(updateWeaponIcons);
PREP(updateRadDisplay);
PREP(updateExternalAtmoDisplay);
PREP(updateSuitTempDisplay);
PREP(updateConsumableDisplay);
PREP(initHUD_US);
PREP(positionsHUD_US);
PREP(bootHUD_US);


PREP(terminateHudInteria);
PREP(bootUp_US);
PREP(suitActivation);
PREP(secondsToBase60Time);
PREP(parseBootUpText);
PREP(addBootUpLine);
PREP(suitDeactivation);
