class CfgCloudlets {
    class Default;

    class exterra_bullets_muzzleRefract : Default
    {
        interval = 0.012;
        circleRadius = 0;
        circleVelocity[] = { 0,0,0 };
        particleShape = "\A3\data_f\ParticleEffects\Universal\Refract";
        particleFSNtieth = 1;
        particleFSIndex = 0;
        particleFSFrameCount = 1;
        particleFSLoop = 0;
        angleVar = 0.5;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 0.2;
        moveVelocity[] = { "5*directionX","5*directionY","5*directionZ" };
        rotationVelocity = 1;
        weight = 0.8;
        volume = 1;
        rubbing = 0;
        size[] = { 1.8,2.4 };
        color[] = { {0.3,0.3,0.3,0.01},{0.3,0.3,0.3,0.26},{0.3,0.3,0.3,0.24},{0.3,0.3,0.3,0.22},{0.3,0.3,0.3,0.16},{0.3,0.3,0.3,0.08},{0.3,0.3,0.3,0.02} };
        animationSpeed[] = { 1.2 };
        //randomDirectionPeriod = 0.1;
        //randomDirectionIntensity = 0.05;
        onTimerScript = "";
        beforeDestroyScript = "";
        destroyOnWaterSurface = 1;
        blockAIVisibility = 0;
        sizeCoef = 0.3;
        colorCoef[] = { 1,1,1,1.4 };
        animationSpeedCoef = 1;
        //position[] = { "positionX + 0.12 * directionLocalX","positionY + 0.12 * directionLocalY","positionZ + 0.12 * directionLocalZ" };
        position[] = { "positionX","positionY","positionZ" };
        lifeTimeVar = 0;
        positionVar[] = { 0,0,0 };
        //MoveVelocityVar[] = { 1,1,1 };
        rotationVelocityVar = 20;
        sizeVar = 0;
        colorVar[] = { 0,0,0,0 };
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
    };
    class exterra_bullets_muzzleDust : Default
    {
        interval = 0.01;
        circleRadius = 0;
        circleVelocity[] = { 0,0,0 };
        particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
        particleFSNtieth = 16;
        particleFSIndex = 12;
        particleFSFrameCount = 8;
        particleFSLoop = 1;
        angleVar = 0.5;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 0.25;
        moveVelocity[] = { "6*directionX","6*directionY","6*directionZ" };
        rotationVelocity = 1;
        weight = 0.01275;
        volume = 0.01;
        rubbing = 0;
        size[] = { 0.3,1.5 };
        color[] = { {0.9,0.9,0.9,0.04},{0.9,0.9,0.9,0.018},{0.9,0.9,0.9,0.006},{0.9,0.9,0.9,0.001} };
        animationSpeed[] = { 1.2 };
        randomDirectionPeriod = 0.1;
        randomDirectionIntensity = 0.05;
        onTimerScript = "";
        beforeDestroyScript = "";
        destroyOnWaterSurface = 1;
        blockAIVisibility = 0;
        sizeCoef = 1.5;
        colorCoef[] = { 1,1,1,0.6 };
        animationSpeedCoef = 1;
        position[] = { "positionX + 0.12 * directionLocalX","positionY + 0.12 * directionLocalY","positionZ + 0.12 * directionLocalZ" };
        lifeTimeVar = 0;
        positionVar[] = { 0,0,0 };
        MoveVelocityVar[] = { 0,0,0 };
        rotationVelocityVar = 20;
        sizeVar = 0;
        colorVar[] = { 0,0,0,0 };
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
        ignoreWind = "true";
    };

    class exterra_bullets_regolithImpactRocks : Default
    {
        interval = "0.01";
		circleRadius = 0;
		circleVelocity[] = {0,0,0};
		particleShape = "\A3\data_f\ParticleEffects\pstone\pstone.p3d";
		animationName = "";
		particleType = "spaceobject";
		timerPeriod = 0.1;
		lifeTime = 4;
		moveVelocity[] = {0,6,0};
		rotationVelocity = 1;
		weight = 1.666667;
		volume = 0.1;
		rubbing = -0.05;
		size[] = {0.1};
		color[] = {{0.1,0.1,0.1,1}};
		animationSpeed[] = {1};
		randomDirectionPeriod = 0;
		randomDirectionIntensity = 0;
		onTimerScript = "";
		beforeDestroyScript = "";
		destroyOnWaterSurface = 1;
		destroyOnWaterSurfaceOffset = -2;
		blockAIVisibility = 0;
		lifeTimeVar = 0;
		positionVar[] = {1,0.5,1};
		MoveVelocityVar[] = {6,9,6};
		rotationVelocityVar = 1;
		sizeVar = 0.05;
		colorVar[] = {0,0,0,0};
		randomDirectionPeriodVar = 0;
		randomDirectionIntensityVar = 0;
    };

    class exterra_bullets_regolithImpactDust : Default
    {
        interval = "0.008";
		circleRadius = 0;
		circleVelocity[] = {0,0,0};
		particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
		particleFSNtieth = 16;
		particleFSIndex = 12;
		particleFSFrameCount = 8;
		particleFSLoop = 0;
		angleVar = 1;
		animationName = "";
		particleType = "Billboard";
		timerPeriod = 0.1;
		lifeTime = "10 + (2.4 * dustness)";
		moveVelocity[] = {"(surfNormalX / 2) * inSpeed / 250 * 0.9","(surfNormalY / 2) * inSpeed / 250 * 0.9","(surfNormalZ / 2) * inSpeed / 250 * 0.9"};
		rotationVelocity = 1;
		weight = 0.14;
		volume = 0.1;
		rubbing = 0.0;
		size[] = {3,6};
		sizeCoef = 1;
		color[] = {{0.2,0.175,0.15,"(0.3 * dustness) + 0.05"},{0.4,0.32,0.25,"(0.21 * dustness) + 0.035"},{0.45,0.37,0.3,"(0.1 * dustness) + 0.016"},{0.45,0.37,0.3,"(0.036 * dustness) + 0.006"},{0.45,0.37,0.3,0}};
		colorCoef[] = {0.3,0.3,0.3,0.3};
		animationSpeed[] = {1};
		animationSpeedCoef = 1.5;
		randomDirectionPeriod = 0.1;
		randomDirectionIntensity = 0.05;
		onTimerScript = "";
		beforeDestroyScript = "";
		destroyOnWaterSurface = 1;
		destroyOnWaterSurfaceOffset = -0.2;
		lifeTimeVar = 0.5;
		position[] = {0,0,0};
		positionVar[] = {0.1,0.1,0.1};
		moveVelocityVar[] = {3,3,3};
		rotationVelocityVar = 0;
		sizeVar = 1;
		colorVar[] = {0.05,0.05,0.05,0.0};
		randomDirectionPeriodVar = 0;
		randomDirectionIntensityVar = 0;
        ignoreWind = "true";
    };
};
